source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"  
gem "jekyll-tagging"        
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "kramdown-parser-gfm"
gem "liquid-md5"
gem "webrick", "~> 1.8"     
